version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8081"
    environment:
      - PORT=8081
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./questions.json:/usr/src/app/questions.json
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    command: npm start
